### ISSUE TITLE
How to use v2.0.0 and the new geography field

### ISSUE THREAD

**Issue by phpMagpie** [masterix21/laravel-addressable#3]
Hi @masterix21 👋 

In the latest code, the  `point(position)` field has been changed to `geography(coordinates)`, but all the POINT helper code that was in the `src\Geo` folder  has been removed.  As a result, I'm struggling on how to save to and read from the coordinates field.

Is 2.0.0 still a work in progress for Laravel 11 users? Should we stick with 1.3.0 for now or is there something I'm missing with how to get 2.0.0 working?

**Comment by masterix21** [comment]
Hi @phpMagpie, thanks for your issue.

I had a mind black-out during the release, sorry. It is now in version 2.0.1.

Feel free to give me feedback. 

Thanks for your effort.
